version: 0.2 

env:
  variables:
    DOCKER_BUILDKIT: "1"

phases:
  build:
    commands:
      - env
      - |
        # export bin PATH
        export PATH=$PATH:$(pwd)/bin
      - |
        docker build -t app --build-arg rand=$RANDOM .
        docker run app sh -c 'echo $rand'
        docker run --name test alpine sh -c 'sleep 1000'
        docker run app sh -c 'echo $rand'
