version: 0.2 

env:
  variables:
    DOCKER_BUILDKIT: "1"

phases:
  build:
    commands:
      - env
      - |
        # export bin PATH
        export PATH=$PATH:$(pwd)/bin
      - |
        docker run --name test alpine sh -c 'sleep 100'
